---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: ledger-api-secrets
  namespace: payments
spec:
  encryptedData:
    DB_PASSWORD: AgBGcjLtgA/MRLXjbx6qHpUSGnZ0BcIdPzxVmwCoXwZrXiUi1tTl9Gu7stNftcvPJoKEAkX4KwTLXwRcACIeRQZrWLD4/KtAnoV9O7YpyafcWU6v0w+h6jBAbXbjK+tOSrzADYs6WaSVAFn4vK3izrkTfMe1kl7Tbq2w8Om0OsDV16QXeB0lvlt5eZpNZxLtqvYZiOkcgtV73bcL7rFfQbTupaiamRnQCTsiKX6dDUxiDTqg9m0Z9mSsvCydJYpmTeZdGMkXOzXc9mdMIxahAU7YP0TM2zyBJTTsDAn32oiqA11KHVgrsCoiuPF0YMEbDxi0evIW55/3FksZ9a9zo1Bgr20NEYo3AzZzO36lbFLs30YssfP7zApwFxzRR/Zyf7hh4sVhS2uFFHF720uXM7rUAEQFW15doX4xxld4y9kDaywhY5WiZWeJOIc/Vv+E9Q/cfp+8QKFv8XrN2xA5b16OeOWPJSn75t5joUEIMsmGrqBAe25OzdsmU08PbjuNjrqGwwyAWJxE4ClaHM0wTz4ClPryn1AqPugkVCZj9E8QQjonu7gCROF7NiIBwGalCMub1nhMubTHLi3xJ8hNaQMOCus1rE7ayTbBASesP53t7woajkSENwrFOZus3n7mrQ1EuHKYeBq6mLbLyAFtBHZbol5Lb7h6yv/EDebUWzIKC4nHznJDciyrP3+oDNSTMaqIm3EV4I7EhLjTNw==
    STRIPE_API_KEY: AgANaoWKHXvgxCgNQmiRooCA08HLk2NdpfCF5GNt5vN/y/JBwJxoZS+TKKAfPQgMjIXkWVQJr9SH2PT8nDqlaHKoLwIhIPtbRJB35k9hgYAbMRkoVta1+XLG3gu+wcat75wM5VNojVIcBIWLbua3ByM45Qo5Jz7ir3ELO9qIXwFvTsuwdH97bgNw0Au4aplxacJb/dzSgZhYPbJIGpzSXBtiXjZoewACq0cIliqryvcm9XyVrpBv3wesfY/Mm7X9z49mqjOMKqolNtN1qFylP3BVZsAGpBRj96HypOGtALftfzXcknKEOcfQYQfZAaAphxE0SAzex7rczyr0iLWYAGyXWvKBm1GPbcfCOuGxXz449kbSrNpaoNV01Wk2LsITiFaj70jK0KHFHVyvP5c69khLdYW0NK5+EHA97BHe45OeQw9rLQp/nBwX+qjBNFNIx5QFXhCUIJqk5odbH3aQS9R/CaLchFLQcSqHl89jHaiBfAQqFMArvRPFz5RP0kH4+HLjn3n1xf7+7T0V+LZ/vZxwtMQtMFic5kqVmLhu16bjTCbMrRaXETpz4ja0KuZAJ2Nmy5NKXdGNgmekRwEyW2sGUUVNZE7ySJEAIPu8HS8qvsT1yA+tNLFAwQ3Jvh04JBIsDSfpyPWqEdpq5rj3/ivmmj58V+7XEzhd0vNkknuNIv+PyuB+FHW8NzmReKOjTDrOvfkbk8aXBAvXAFjhNqwjahmqTNenZ8r6YGpU4g==
  template:
    metadata:
      name: ledger-api-secrets
      namespace: payments
